[package]
name = "syx-rpc-rust-demo-api"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
syx-rpc-rust-core.workspace = true
syx-rpc-rust-macro.workspace = true
serde_json = "1.0.114"